// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenUApi.Migrations
{
    [DbContext(typeof(greenUDB))]
    [Migration("20250326153421_LineRefactorMigration")]
    partial class LineRefactorMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("accesToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("accesToken_expire_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("accountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("impersonateBy")
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .HasColumnType("longtext");

                    b.Property<int>("providerId")
                        .HasColumnType("int");

                    b.Property<string>("refreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("refreshToken_expire_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("scope")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Domain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Domain");
                });

            modelBuilder.Entity("GreenUApi.model.Garden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Latitude")
                        .HasColumnType("float");

                    b.Property<float>("Length")
                        .HasColumnType("float");

                    b.Property<float>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Update_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<float>("Width")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Garden");
                });

            modelBuilder.Entity("GreenUApi.model.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("Length")
                        .HasColumnType("float");

                    b.Property<int>("ParcelId")
                        .HasColumnType("int");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Update_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("VegetableId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParcelId");

                    b.HasIndex("VegetableId");

                    b.ToTable("Line");
                });

            modelBuilder.Entity("GreenUApi.model.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Garden_id")
                        .HasColumnType("int");

                    b.Property<int>("Line_id")
                        .HasColumnType("int");

                    b.Property<int>("Parcel_id")
                        .HasColumnType("int");

                    b.Property<byte>("PreviousStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("Update_at")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Garden_id");

                    b.HasIndex("Line_id");

                    b.HasIndex("Parcel_id");

                    b.ToTable("Todo");
                });

            modelBuilder.Entity("GreenUApi.model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Is_admin")
                        .HasColumnType("int");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Postal_code")
                        .HasColumnType("longtext");

                    b.Property<string>("Salt")
                        .HasColumnType("longtext");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("eventType")
                        .HasColumnType("longtext");

                    b.Property<string>("ip_adress")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("Param", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<short>("NotActive")
                        .HasColumnType("smallint");

                    b.Property<int>("domain_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("domain_id");

                    b.ToTable("Param");
                });

            modelBuilder.Entity("Parcel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("Garden")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("garden_id")
                        .HasColumnType("int");

                    b.Property<float>("height")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("nbLignes")
                        .HasColumnType("int");

                    b.Property<float>("width")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("Garden");

                    b.ToTable("Parcel");
                });

            modelBuilder.Entity("Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("eventType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("expire_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("impersonateBy")
                        .HasColumnType("longtext");

                    b.Property<string>("ip_adress")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("user_agent")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Vegetable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("comments")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<short>("cultivationUnderShader")
                        .HasColumnType("smallint");

                    b.Property<short>("directSeeding")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("end_of_plenting")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("familyId")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<DateTime>("start_of_plenting")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("start_of_sowing")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("variety")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("vegetable")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Vegetable");
                });

            modelBuilder.Entity("Verification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("expire_at")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("update_at")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Vérification");
                });

            modelBuilder.Entity("Account", b =>
                {
                    b.HasOne("GreenUApi.model.User", "User")
                        .WithMany("Account")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenUApi.model.Garden", b =>
                {
                    b.HasOne("GreenUApi.model.User", "User")
                        .WithMany("Gardens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenUApi.model.Line", b =>
                {
                    b.HasOne("Parcel", "Parcel")
                        .WithMany("lines")
                        .HasForeignKey("ParcelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vegetable", "Vegetable")
                        .WithMany("lines")
                        .HasForeignKey("VegetableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcel");

                    b.Navigation("Vegetable");
                });

            modelBuilder.Entity("GreenUApi.model.Todo", b =>
                {
                    b.HasOne("GreenUApi.model.Garden", "Garden")
                        .WithMany()
                        .HasForeignKey("Garden_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GreenUApi.model.Line", "Line")
                        .WithMany()
                        .HasForeignKey("Line_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parcel", "Parcel")
                        .WithMany("todos")
                        .HasForeignKey("Parcel_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garden");

                    b.Navigation("Line");

                    b.Navigation("Parcel");
                });

            modelBuilder.Entity("Log", b =>
                {
                    b.HasOne("GreenUApi.model.User", "User")
                        .WithMany("Logs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Param", b =>
                {
                    b.HasOne("Domain", "Domain")
                        .WithMany("Params")
                        .HasForeignKey("domain_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Domain");
                });

            modelBuilder.Entity("Parcel", b =>
                {
                    b.HasOne("GreenUApi.model.Garden", "garden")
                        .WithMany()
                        .HasForeignKey("Garden")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("garden");
                });

            modelBuilder.Entity("Session", b =>
                {
                    b.HasOne("GreenUApi.model.User", "User")
                        .WithMany("Session")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Verification", b =>
                {
                    b.HasOne("GreenUApi.model.User", "User")
                        .WithMany("Verification")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain", b =>
                {
                    b.Navigation("Params");
                });

            modelBuilder.Entity("GreenUApi.model.User", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Gardens");

                    b.Navigation("Logs");

                    b.Navigation("Session");

                    b.Navigation("Verification");
                });

            modelBuilder.Entity("Parcel", b =>
                {
                    b.Navigation("lines");

                    b.Navigation("todos");
                });

            modelBuilder.Entity("Vegetable", b =>
                {
                    b.Navigation("lines");
                });
#pragma warning restore 612, 618
        }
    }
}
